[package]
name = "git-factor"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "git-factor"
path = "src/bin/git-factor.rs"

[[bin]]
name = "git-sequence-editor"
path = "src/bin/git-sequence-editor.rs"

[dependencies]
clap = { version = "4.5.56", features = ["derive"] }
thiserror = "2.0.18"

[dev-dependencies]
proptest = "1.9.0"
tempfile = "3.24.0"
